name: advanced_structure_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.1.beta <4.0.0'

dependencies:
  flutter:
      sdk: flutter
  analyzer: ^6.3.0
  dio: ^5.4.0
  flutter_svg: ^2.0.7
  json_serializable: ^6.7.1
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.6
  build_runner: ^2.4.7
  
flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/images/hollow_circle_ic.svg
    - assets/images/left_arrow_ic.svg
        
